- id: configuration_files_templating
  name: Configuration files templating
  description: Run configuration files templating
  entry: hooks/hook_configuration_files_templating.sh
  language: script
  require_serial: true
